language: go
sudo: true

script:
- sudo apt-get install fuse appstream appstream-util git
- BUILD_SRC="$(pwd)"
# external downloads
- wget https://github.com/probonopd/uploadtool/raw/master/upload.sh; chmod +x upload.sh
- wget https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage; mv linuxdeployqt* linuxdeployqt; chmod +x linuxdeployqt
- wget https://github.com/syncthing/syncthing/releases/download/v1.9.0/syncthing-source-v1.9.0.tar.gz
- git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
# preparation
- . $HOME/.asdf/asdf.sh
- asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
- asdf install golang 1.14
- asdf global golang 1.14
# unpacking
- tar xzf syncthing-*.tar.gz && rm *.tar.gz
- ls -l
- BUILD_DIR="${BUILD_SRC}/syncthing"
# building syncthing
- cd "${BUILD_DIR}"
- go version
- go run build.go
# configuring appimage
- cd "${BUILD_SRC}"
- mkdir AppDir
- APPDIR="${BUILD_SRC}/AppDir"
- mkdir -p "${APPDIR}/usr/share"
- mv syncthing "${APPDIR}/usr/share"
# building appimage
- export ARCH=x86_64
- |
  ./linuxdeployqt AppDir/usr/share/syncthing/syncthing \
  -updateinformation="gh-releases-zsync|zilti|syncthing|continuous|syncthing*.AppImage.zsync" \
  -appimage
- bash upload.sh ./*.AppImage*
